/* COMMON */
export const BEGIN_AJAX_CALL = 'BEGIN_AJAX_CALL';
export const SHOW_IDENT_MENU_SUCCESS = 'SHOW_IDENT_MENU_SUCCESS';
export const HIDE_IDENT_MENU_SUCCESS = 'HIDE_IDENT_MENU_SUCCESS';

/* VEHICLES - CUSTOMERS */
export const CREATE_VEHICLE = 'CREATE_VEHICLE';
export const LOAD_VEHICLES_SUCCESS = 'LOAD_VEHICLES_SUCCESS';
export const CREATE_CUSTOMER  = 'CREATE_CUSTOMER';
export const LOAD_CUSTOMERS_SUCCESS = 'LOAD_CUSTOMERS_SUCCESS';
export const CREATE_VEHICLE_SUCCESS = 'CREATE_VEHICLE_SUCCESS';
export const UPDATE_VEHICLE_SUCCESS = 'UPDATE_VEHICLE_SUCCESS';

/* PROFILE */
export const CREATE_PROFILE_SUCCESS = 'CREATE_PROFILE_SUCCESS';
export const LOG_IN_SUCCESS = 'LOG_IN_SUCCESS';
export const LOG_OUT_SUCCESS = 'LOG_OUT_SUCCESS';
export const CLEAR_STORE_SUCCESS  = 'CLEAR_STORE_SUCCESS';




